repositories:
# To use official "stable" charts a.k.a https://github.com/helm/charts/tree/master/stable
- name: stable
  url: https://charts.helm.sh/stable
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: postgres
  namespace: challenge
  chart: bitnami/postgresql
  version: 11.2.5
- name: minio
  namespace: challenge
  chart: bitnami/minio
  version: 11.5.1
  set:
    - name: auth.rootPassword
      value: password
    - name: defaultBuckets
      value: backups
- name: challenge-api
  namespace: challenge
  chart: ./deploy/api-challenge
- name: registry
  namespace: registry
  chart: bitnami/harbor
  set:
    - name: adminPassword
      value: password